#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  3 12:49:08 2020

@author: ernie
"""

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsScene, QGraphicsView, QGraphicsTextItem, QApplication, QMainWindow, QLabel 
from PyQt5.Qt import Qt
from assignment12C import outPutFor2C
from PyQt5.QtGui import QPixmap

class Ui_Form(object):

    def openwindow(self, valueToTransfer):

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Page2()
        self.ui.setupUi(self.window, valueToTransfer)
        
        Form.hide()
        self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(734, 428)
        self.label_imageDirectoryAndName = QtWidgets.QLabel(Form)
        self.label_imageDirectoryAndName.setGeometry(QtCore.QRect(0, 130, 461, 31))
        self.label_imageDirectoryAndName.setObjectName("label_imageDirectoryAndName")
        self.label_imageDirectoryAndName.setTextInteractionFlags(Qt.TextSelectableByMouse)
        
        self.label_imageSliceValue = QtWidgets.QLabel(Form)
        self.label_imageSliceValue.setGeometry(QtCore.QRect(0, 160, 461, 21))
        self.label_imageSliceValue.setObjectName("label_imageSliceValue")
        self.label_imageSliceValue.setTextInteractionFlags(Qt.TextSelectableByMouse)
        
        self.label_imageDirection = QtWidgets.QLabel(Form)
        self.label_imageDirection.setGeometry(QtCore.QRect(0, 190, 461, 21))
        self.label_imageDirection.setObjectName("label_imageDirection")
        self.label_imageDirection.setTextInteractionFlags(Qt.TextSelectableByMouse)
        
        self.txt_input_imageDirectoryAndName = QtWidgets.QLineEdit(Form)
        self.txt_input_imageDirectoryAndName.setGeometry(QtCore.QRect(380, 140, 201, 21))
        self.txt_input_imageDirectoryAndName.setObjectName("txt_input_imageDirectoryAndName")
        
        self.txt_input_imageSliceValue = QtWidgets.QLineEdit(Form)
        self.txt_input_imageSliceValue.setGeometry(QtCore.QRect(380, 165, 201, 21))
        self.txt_input_imageSliceValue.setObjectName("txt_input_imageSliceValue")
        
        self.txt_input_imageDirection = QtWidgets.QLineEdit(Form)
        self.txt_input_imageDirection.setGeometry(QtCore.QRect(380, 190, 201, 21))
        self.txt_input_imageDirection.setObjectName("txt_input_imageDirection")
        
        
        self.btn_submit = QtWidgets.QPushButton(Form)
        self.btn_submit.setGeometry(QtCore.QRect(380, 240, 211, 32))
        self.btn_submit.setObjectName("btn_submit")
        
        self.text_title = QtWidgets.QTextEdit(Form)
        self.text_title.setGeometry(QtCore.QRect(60, 10, 629, 51))
        self.text_title.setObjectName("text_title")
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login Page"))
        self.label_imageDirectoryAndName.setText(_translate("Form", "Enter ImageDirection And Image Name, ex: 'images/t1.nii' :"))
        self.label_imageSliceValue.setText(_translate("Form", "Enter Slice value, ex '250' : "))
        self.label_imageDirection.setText(_translate("Form", "Enter Direction, ex 'axial' or 'sagittal' or 'coronal' : "))
        
        self.btn_submit.setText(_translate("Form", "Submit"))



        self.text_title.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                   "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                   "p, li { white-space: pre-wrap; }\n"
                                                   "</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                   "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#cf0f39;\">Viewer For Question 2c </span></p></body></html>"))
        

        self.btn_submit.clicked.connect(self.btn_submit_handler)


    def btn_submit_handler(self):

        imageDirectoryAndName = self.txt_input_imageDirectoryAndName.text()
        imageSliceValue = self.txt_input_imageSliceValue.text()
        imageDirection = self.txt_input_imageDirection.text()
        
        valueTransferForNextPage = []
        valueTransferForNextPage.append(imageDirectoryAndName)
        valueTransferForNextPage.append(imageSliceValue)
        valueTransferForNextPage.append(imageDirection)
        
        self.openwindow(valueTransferForNextPage)
        
        #Page2.show()
        #self.ui.btn_sumbit.clicked.connect(lambda : self.ui.stackedWidget.setCurrentIndex(0))


class Ui_Page2(object):

    def openwindow(self):

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Page2, valueToTransfer):

        Page2.setObjectName("Page2")
        Page2.resize(800, 1000)
        
        imageDirectoryAndName = valueToTransfer[0]
        imageSliceValue = int(valueToTransfer[1])
        imageDirection = valueToTransfer[2]

        print(imageDirectoryAndName,imageSliceValue,imageDirection)        
        outPutFor2C(imageDirectoryAndName, imageSliceValue, imageDirection)                
        print(imageDirectoryAndName,imageSliceValue,imageDirection)
        
        rawImage = QPixmap(imageDirection).scaledToWidth(256)
        self.rawImageLabel = QLabel(Page2)
        self.rawImageLabel.setPixmap(rawImage)
        self.rawImageLabel.setGeometry(0, 50, rawImage.width(), rawImage.height())
        
        self.rawImageLabelTitle = QLabel(Page2)
        self.rawImageLabelTitle.setText("raw Image")
        self.rawImageLabelTitle.setGeometry(0, 30, rawImage.width(), 20)
        
        fftRawImage = QPixmap("fftRawImage.png").scaledToWidth(256)
        self.fftRawImage = QLabel(Page2)
        self.fftRawImage.setPixmap(fftRawImage)
        self.fftRawImage.setGeometry(0, 500, fftRawImage.width(), fftRawImage.height())
        
        self.fftRawImagelTitle = QLabel(Page2)
        self.fftRawImagelTitle.setText("fft(raw image)")
        self.fftRawImagelTitle.setGeometry(0, 480, rawImage.width(), 20)
        
        rawImageAfterEdgeEnhancement = QPixmap("rawImageAfterEdgeEnhancement.png").scaledToWidth(256)
        self.rawImageAfterEdgeEnhancement = QLabel(Page2)
        self.rawImageAfterEdgeEnhancement.setPixmap(rawImageAfterEdgeEnhancement)
        self.rawImageAfterEdgeEnhancement.setGeometry(500, 50, rawImageAfterEdgeEnhancement.width(), rawImageAfterEdgeEnhancement.height())
        
        self.rawImageAfterEdgeEnhancementTitle = QLabel(Page2)
        self.rawImageAfterEdgeEnhancementTitle.setText("raw image after edge enhancement")
        self.rawImageAfterEdgeEnhancementTitle.setGeometry(500, 30, rawImage.width(), 20)
        
        
        rawImageAfterSmoothing = QPixmap("rawImageAfterSmoothing.png").scaledToWidth(256)
        self.rawImageAfterSmoothing = QLabel(Page2)
        self.rawImageAfterSmoothing.setPixmap(rawImageAfterSmoothing)
        self.rawImageAfterSmoothing.setGeometry(500, 510, rawImageAfterSmoothing.width(), rawImageAfterSmoothing.height())
        
        
        self.rawImageAfterSmoothingTitle = QLabel(Page2)
        self.rawImageAfterSmoothingTitle.setText("raw image after smoothing")
        self.rawImageAfterSmoothingTitle.setGeometry(500, 470, rawImage.width(), 20)
        
        
        self.btn_back = QtWidgets.QPushButton(Page2)
        self.btn_back.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Page2)
        QtCore.QMetaObject.connectSlotsByName(Page2)

    def retranslateUi(self, Page2):
        _translate = QtCore.QCoreApplication.translate
        Page2.setWindowTitle(_translate("Page2", "Form"))
        
        self.btn_back.setText(_translate("Page2", "Back"))
        self.btn_back.clicked.connect(self.button_handler_back)

    def button_handler_back(self):
        self.openwindow()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()

    sys.exit(app.exec_())